# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: fede1e7587ce9654093585545a808ddfb428930f7a85672d921905c824186da734906ec121f2a5b2bcd2aa1c64390610a0ebb6e652b6d69d5ce84aba060f8c72
  mail_username: test@test.com
  mail_password: password
  # google_client_id: 536915156403-1ooff7tfsotdmbdnq4ot7crvt0tg4pjh.apps.googleusercontent.com
  # google_client_secret: l7iHOyciPgExAGL8xTxTfBbe
test:
  secret_key_base: fa533ebec7959393067ef100d21c96d8242129f31987fae41958d68c29b33a1032c97b593c14a6cbff4775c0543eaec003c80fb4e93574c98d32cd347bad2e43

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
